### ISSUE TITLE
tagSet metadata

### ISSUE THREAD

**Issue by ksuderman** [lappsgrid-incubator/gold-lif#1]
In the `contains` section of a View's metadata there are currently at least four different `tagSet` type attributes:

1. `posTagSet`
1. `namedEntityCategorySet`
1. `categorySet`
1. `dependencySet`

Could we come up with a generic name, say `tagSet`, that could be used for all of the above?  They all serve the same purpose and using a consistent name make serializing the JSON to/from the Java classes much easier.

**Comment by marcverhagen** [comment]
That is what we had and I think it was a conscious decision to use different names. Not sure what our state of mind was when we did that an do do not remember the reasoning, but this is now encoded in the vocabulary.

**Comment by ksuderman** [comment]
Right you are... I don't remember us deciding this and it is the kind of thing I'm usually against, but the changes to the vocabulary were made nine months ago.
